### ISSUE TITLE
Docker path mismatch between fluentd.daemonset.yaml and source.docker.conf

### ISSUE THREAD

**Issue by ryanwalls** [SumoLogic/fluentd-kubernetes-sumologic#10]
In `fluentd.daemonset.yaml` the mount path is specified as `/var/lib/docker`:
```
       - name: docker-logs
          mountPath: /var/lib/docker/
          readOnly: true
```

But in `source.docker.conf`, it is reading from ` /mnt/log/`.  
```
<source>
  type tail
  format /^time="(?<time>[^)]*)" level=(?<severity>[^ ]*) msg="(?<message>[^"]*)"( err="(?<error>[^"]*)")?( statusCode=($<status_code>\d+))?/
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  path /mnt/log/docker.log
  pos_file /mnt/pos/ggcp-docker.log.pos
  tag docker
</source>
```

**Comment by stevezau** [comment]
hmm in my kubernetes deployment /var/lib/docker/docker.log does not even exist.

can you see a docker.log on yours?

**Comment by ryanwalls** [comment]
@stevezau Mine is weird due to rancher.  Mine is in `/var/log/upstart/docker.log`. 

I'm just pointing out that the paths between the mount path specified in `fluentd.daemonset.yaml` and the source path in `source.docker.conf` should match.

**Comment by stevezau** [comment]
It does not even exist on mine.. not sure what to do here in terms of having a standard path. 

for now i'll fix the incorrect path mapping

**Comment by ryanwalls** [comment]
@stevezau I think you can close this.  The `fluentd.daemonset.yaml` being an example, the end users can change to their host path.  Maybe just add a line to the readme?  Or a line comment in the `fluentd.daemonset.yaml` file?
