### ISSUE TITLE
Failed to list *v1.Node: nodes is forbidden: User \"system:serviceaccount:kube-system:heapster\" cannot list nodes at the cluster scope"

### ISSUE THREAD

**Issue by syst0m** [SumoLogic/fluentd-kubernetes-sumologic#101]
Followed this tutorial:
https://help.sumologic.com/07Sumo-Logic-Apps/01Amazon_and_AWS/Amazon_EKS/Collect_Logs_for_Amazon_EKS

heapster pod is failing with:
`"E1210 17:07:16.127337       1 reflector.go:190] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *v1.Namespace: namespaces is forbidden: User \"system:serviceaccount:kube-system:heapster\" cannot list namespaces at the cluster scope"`

None of the dashboards from the EKS app on SL are working.

**Comment by frankreno** [comment]
@syst0m : Look like the RBAC config.  Can you please apply this to the cluster as well and see if this resolves the issue?

https://github.com/kubernetes-retired/heapster/blob/master/deploy/kube-config/rbac/heapster-rbac.yaml

**Comment by frankreno** [comment]
@syst0m did the above resolve the issue?

**Comment by syst0m** [comment]
@frankreno Sorry, priorities shifted on another part of the project. 
I will have to sort out logging at a later stage. 
Thanks for the help, it is much appreciated!

**Comment by frankreno** [comment]
@syst0m based on the error I am confident that is the issue, so I am going to close this out for the moment.  If you still have issues, feel free to reopen.
