### ISSUE TITLE
Logs suddenly stop being ingested into SumoLogic

### ISSUE THREAD

**Issue by tjensen** [SumoLogic/fluentd-kubernetes-sumologic#104]
We have been having intermittent problems ingesting logs from our Kubernetes 1.9.7 cluster for a while, using fluentd-kubernetes-sumologic. We opened a support ticket with SumoLogic regarding this issue but they suggested that we open an issue on this GitHub project.

The issue is that, at some random point, we stop getting logs in SumoLogic from some individual nodes. If we delete the corresponding fluentd pod, the issue resolves itself, but eventually recurs.

We've spent a fair amount of time debugging this issue, and believe it might be an issue at the SumoLogic server, because:

1. The fluentd process seems healthy (it's position files are getting updated; it's not logging any errors; etc).
2. The pod's Tx Rate over the network doesn't change at the time the logs stop getting ingested in SumoLogic
3. The ingest volume, as reported by the SumoLogic Data Volume Index also doesn't change at the time the logs stop getting ingested.

We picked a random host that this happened to on the evening of Dec 19th; in the screenshots, you can see that between 9:45 and 10pm (CST), queries stop returning any logs for that host:
![screen shot 2018-12-19 at 1 00 10 pm](https://user-images.githubusercontent.com/798166/50291864-5194e100-0435-11e9-85cd-ca77a44ee279.png)

However, there is no corresponding change in pod network transmit rate or SumoLogic ingest volume at that time:
![screen shot 2018-12-19 at 12 59 42 pm](https://user-images.githubusercontent.com/798166/50291903-68d3ce80-0435-11e9-8ce1-8dabbf95b175.png)
![screen shot 2018-12-19 at 12 59 53 pm](https://user-images.githubusercontent.com/798166/50291922-71c4a000-0435-11e9-9bf7-f5eaf27f962a.png)

This only happened for that particular host at that time (although another host had the same problem about an hour later).

We have already tried setting `ENABLE_STAT_WATCHER` to `false` but it did not resolve the issue; logs still suddenly stopped being ingested into SumoLogic.

What is causing SumoLogic to stop ingesting our logs, even though the fluentd pods appear to be sending the logs to SumoLogic? As mentioned above, the fluentd pods are not logging any errors when this happens.

**Comment by frankreno** [comment]
@tjensen - I spoke with our support team who I believe you were working with and I believe this now resolved but was a separate issue.  Can you please confirm?

**Comment by tjensen** [comment]
@frankreno Yes, I think we can close this issue. Thank you.

**Comment by xrismck** [comment]
I'm curious what the cause and resolution were here.
