### ISSUE TITLE
Unreadable log files error

### ISSUE THREAD

**Issue by ryanwalls** [SumoLogic/fluentd-kubernetes-sumologic#11]
Hopefully last road block.  For some reason the mounted container logs are not readable by the fluentd container.  

```
/mnt/log/containers/fluentd-48fc6_default_fluentd-736a8af93bb05b2d247c994ea6177952e16e14137bd01f03e682a465a9725d2d.log unreadable. It is excluded and would be examined next time.
```

I've tried running as privileged, but not luck.  Perhaps you've hit this before and know a solution?

**Comment by ryanwalls** [comment]
I didn't have the location the symlinks were pointing to mounted as well.  I had `/var/log/containers` but didn't mount `/var/lib/docker`.

**Comment by salilgupta1** [comment]
I'm having this same issue: 
```
/mnt/log/containers/kube-apiserver-ip-10-131-51-160.ec2.internal_kube-system_kube-apiserver-c7a8163d649d8c56993670717b8aaa72704a7a9930aa115bd45971072f0ac96d.log unreadable. It is excluded and would be examined next time
```
I deployed the DaemonSet and Secret on my K8s cluster following the directions of the README file. 

My cluster is running on K8s v1.6. I was able to get this to work on my K8s cluster that was running v1.5. 

Has anyone seen this issue on v1.6?
