### ISSUE TITLE
RuntimeError "can't add a new key into hash during iteration" (fixed in fluent-plugin-concat v2.2.3)

### ISSUE THREAD

**Issue by emptywee** [SumoLogic/fluentd-kubernetes-sumologic#112]
After upgrading from fluentd-kubernetes-sumologic v2.0.0 to v2.3.0 we ran into the issue where it would stop sending logs to sumo and print errors similar to described in this issue: https://github.com/fluent-plugins-nursery/fluent-plugin-concat/issues/49

I rebuilt fluentd-kubernetes-sumologic image with the concat plugin v2.2.3 and so far haven't seen this error and logs are being sent properly to SumoLogic. I am not 100% sure that exactly this bug caused logs to be not shipped to SumoLogic, and I can see that we've been using concat plugin v2.2.1 for quite a while, but I haven't seen those errors before. Not really sure what other change could've caused such errors to pop up. But just to be on the safe side, I believe it'd be good to update dependencies to use v2.2.3+ of the concat plugin.

**Comment by bin3377** [comment]
Fixed. will be included in next release cut
