### ISSUE TITLE
Release as an independent GEM

### ISSUE THREAD

**Issue by zonzamas** [SumoLogic/fluentd-kubernetes-sumologic#114]
Do you plan to release this PR as an independent GEM? I would love to use it in a different fluentd image.

**Comment by bin3377** [comment]
yes. this is in scope. but need to restructure the repo a little

**Comment by bin3377** [comment]
addressing in https://github.com/SumoLogic/fluentd-kubernetes-sumologic/pull/122

**Comment by zonzamas** [comment]
:muscle:
