### ISSUE TITLE
Any way to disable logging for some particular pod through annotations?

### ISSUE THREAD

**Issue by emptywee** [SumoLogic/fluentd-kubernetes-sumologic#12]
Is it possible to disable shipping logs for particular pods by setting some param in annotation? My bet it's not yet possible, but any plans to add this feature? Since SumoLogic is typically paid by volume, would be nice to control what deployments/pods must ship their logs to the SumoLogic cloud.

Thank you.

**Comment by stevezau** [comment]
Right now you can do this by editing https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/conf.d/source.containers.conf#L9 and adding an exclude rule http://docs.fluentd.org/v0.12/articles/in_tail#excludepath

We could do it via annotations but that means fluentd still has to process and throw out the data. The exclude rule means it will never get to fluentd.

Happy for you to open a PR if you want the annotation feature.

**Comment by emptywee** [comment]
Thank you for the hint. Still, for end-users (especially new like me) annotations seem to be a more straight-forward way. I don't mind if fluentd has to process but throw away the data :-) 

I am yet too new to file PRs to this. Thought that if it wasn't too hard, I'd request this feature. Might be helpful for others too.

**Comment by stevezau** [comment]
@frankreno you want to take a look at this?

**Comment by frankreno** [comment]
@stevezau : rather than using an annotation on the various pods you deploy to exclude, does it make more sense to have an env var with some regex to exclude a pod, container, namespace or host on the fluentd.daemonset.yaml.  Perhaps both is a good solution.

**Comment by frankreno** [comment]
@stevezau : mind reviewing https://github.com/SumoLogic/fluentd-kubernetes-sumologic/pull/16 before I merge?

**Comment by frankreno** [comment]
@emptywee : image has been pushed to docker hub with the changes.

**Comment by emptywee** [comment]
Thanks! I really appreciate it. Now we can save some traffic (and money)!

**Comment by tasdikrahman** [comment]
Greetings @emptywee , @frankreno . I was wondering how would one try to have multiple pod regexes to be ignored by the env var `EXCLUDE_POD_REGEX`, the same approach has been described in https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/62, how would you suggest going ahead with it? Thanks

**Comment by emptywee** [comment]
`(pod_name_1|pod_name_2|pod_name_3)` as a regex?
