### ISSUE TITLE
Sumologic sourceCategory not respecting sumologic.com/sourceCategory annotation

### ISSUE THREAD

**Issue by adamcheney** [SumoLogic/fluentd-kubernetes-sumologic#131]
Hi folks,

I'm probably being an idiot, but I cannot get the sourceCategory annotation to work. This is set at the pod level. I'm running this in an EKS cluster on AWS.

Everything is pretty standard, I think - I run the fluentd containers in a daemonset. My dockerfile installs both the Sumologic output plugin and this Sumologic kubernetes filter plugin:
`
    gem install fluent-plugin-sumologic_output -v 1.4.1 && \
    gem install fluent-plugin-kubernetes_sumologic -v 2.3.1 && \
`

I use a single fluentd config file, installed by a configmap - for customer workloads, it tails the docker logs from /var/log/containers on the nodes. After dealing with "system" logs (these are sent to Cloudwatch) I use the kubernetes_metadata plugin to grab annotations, then check the events for the annotation 

> sumologic.com/include: "true"

 If it's set, the annotation

> sumologic.com/sourceCategory:

is checked - we want to allow customers to define their own sourceCategories within rules we set, so this is checked against a regex. If it's null, the event is sent to sumologic with `source_catagory` set to `"#{ENV['SOURCE_CATEGORY']}"` (this works perfectly). If the annotation is set but doesn't match our regex, it is sent to Cloudwatch (this works perfectly).

If the annotation is set and matches the regex, I send the even to sumologic but do not set the `source_category` key. My assumption was that the value of the annotation would take over and _sourceCategory would be set correctly - but it isn't, the event is given the default source category associated with the collector URL.

Is there a way of getting the events sent to the source category set in the annotation `cloudwatch.com/sourceCategory'?

**Comment by awcheney** [comment]
OK, I found the problem. The `source_category_prefix` defaults to 'kubernetes' in the ruby, so all my logs were going to 'kubernetes/<whatever_sourcecategory_I_set>' and my role didn't allow me to see them.

If you don't want to use a prefix, you can't set this to blank, even explicitly in the config file. So, I forked the repo and set it to an empty string. I suspect my use-case is unique enough that a fork is better than a PR, but if others disagree, it's a simple change for me to push to origin.

**Comment by frankreno** [comment]
@awcheney great find.  As long as it does not break current behavior, we would welcome a PR.  Seems like a good add to me.
