### ISSUE TITLE
ls: cannot access '/fluentd/etc/fluent.file.conf': No such file or directory

### ISSUE THREAD

**Issue by andrews32** [SumoLogic/fluentd-kubernetes-sumologic#135]
I last deployed a daemonset 12 days ago. Today, using the same YAML but containers are going into CrashLoopBackOff. This is the error in the container log:

`ls: cannot access '/fluentd/etc/fluent.file.conf': No such file or directory`
`Unknown source 'file'`

I think there has been a major change between v2.3.1 and v2.4.0. I noticed this file (https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/daemonset/nonrbac/fluentd.yaml) was once only 50 lines, but is now 1524 lines!

I'm trying to understand the big change and why that change wouldn't be backwards compatible?

**Comment by prasadjjoshi** [comment]
I struggled with this issue and fluentd pods in my K8 cluster never came back from crashloopbackoff to running state.  I had to hardcode image v2.3.1 to get the pods into running state.
containers:
      - image: sumologic/fluentd-kubernetes-sumologic:v2.3.1

**Comment by samjsong** [comment]
Thank you for bringing this issue to our attention. In version `v2.3.1`, the Fluentd conf files that specify the inputs and the various config options for the many Fluentd plugins was baked into the Docker image itself, meaning the only way to change these options was if we exposed these options as ENV variables, and the Daemonset was deployed with the desired ENV variables.

The reason for the massive increase in number of lines in the version `v2.4.0` `fluentd.yaml` file is that ALL of the Fluentd conf is now exposed in the `fluentd.yaml` file itself. Thus anyone deploying the Fluentd Daemonset can now fine-tune the various options for any of the Fluentd plugins to their liking.

Unfortunately what we did not realize was that this meant the `latest` tagged Docker image would be missing these Fluentd conf files that we pulled out of the Docker image and into the `fluentd.yaml` file.

We apologize for the inconvenience. To resolve this issue, we've cut two new releases, `v2.3.2` and `v2.4.1`, which each respectively point to the explicit version of the Docker image in the yaml files. In addition, the `latest` tag now points to `v2.3.2`, which should be exactly the same as `v2.3.1`. We'll be updating the master branch to explicitly reference the `v2.4.1` Docker image as well, and continue to update the version as we cut new releases.

**Comment by andrews32** [comment]
I see v2.4.2 was released 3 days ago, we're getting this same error again.

`ls: cannot access '/fluentd/etc/fluent.file.conf': No such file or directory`

**Comment by samjsong** [comment]
Thank you again for bringing this to our attention. We sincerely apologize for the miss. The `latest` tag should again point to `v2.3.2`, and we'll be making the relevant changes to our automation process to ensure this does not happen again.
