### ISSUE TITLE
When a container is restarted, first ~50 seconds of logs are lost

### ISSUE THREAD

**Issue by mfornasa** [SumoLogic/fluentd-kubernetes-sumologic#14]
We noticed that first ~50 seconds of logs after a container startup are not captured.

For example:
* I started a container at `12:50:00`
* After 50 seconds, Sumologic pods logs the following: 
```
2017-02-15 12:50:42 +0000 [info]: following tail of /mnt/log/containers/my-pod-name-87d9f1b535e11c02690567e7b4bb65016346c263b683c96f720b90e52ca6982e.log
```
* Logs between `12:50:00` and `12:50:42` are lost.

This is a showstopper for us. Not only we are loosing logs, but we are loosing the most important log entries (application startup). Crashing application are not showing any log!

**Comment by stevezau** [comment]
Hi @mfornasa this repo used fluentd tail plugin. I suspect maybe the files are disappearing before the tail plugin can pick it up.

I wonder if there are some docker/kube settings we can tune to keep it around for longer or perhaps the better solution is to look at using the native fluentd driver as suggested in #9

**Comment by frankreno** [comment]
@mfornasa  bc96bcc should fix this issue.  I need to work on getting this pushed to Dockerhub though.  Will update once available.

**Comment by frankreno** [comment]
@mfornasa: new image with the fix is now available in docker hub

**Comment by mfornasa** [comment]
@frankreno seems good. Thanks!
