### ISSUE TITLE
kube-apiserver is too spammy and I can not exclude it

### ISSUE THREAD

**Issue by mfornasa** [SumoLogic/fluentd-kubernetes-sumologic#17]
On one of my clusters, `kube-apiserver` generates a lot of messages (more than 400 MB/day).

Unfortunately, it seems that I can not use `EXCLUDE_*` to filter Kubernetes components collected [here](https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/conf.d/source.kubernetes.conf). 

Maybe we can filter `severity I` messages as suggested to me by @fikander, but a mechanism similar to the `EXCLUDE` ones would be more general.

P.S. This is not related to: https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/13

**Comment by frankreno** [comment]
@mfornasa :There are multiple ways to filter the data.  if you want to do it at the source.kubernetes.conf, you would need to use the fluentd tail plugin option, exclude_path, which I believe does not accespt regex.  You can also use some environment variables to specify a regex pattern to exclude by host, pod, namespace or container.  This is documented in the README in the options section.  Does this not meet your requirement?

**Comment by mfornasa** [comment]
@frankreno my understanding is that all the `EXCLUDE` options operate only on containers that are collected trough `source.containers.conf`.

The problem here is with a Kubernetes component called `kube-apiserver` which is explicitly collected trough `source.kubernetes.conf` (in [this](https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/8d3fcd43d0ae458c9f321b2fee2d8d67e5b70aea/conf.d/source.kubernetes.conf#L72) line). So, I don't see a way to exclude logs from `kube-apiserver` using `EXCLUDE` directives. 

This is a generic problem, as `kube-apiserver` is installed part of Kubernbetes.

**Comment by frankreno** [comment]
@mfornasa : My apologies, I see now.  So we need to expose the environment variables in the  `source.kubernetes.conf` and that should then give you this capability.  I will look at this as soon as I can.

**Comment by mfornasa** [comment]
Any news on this?

**Comment by frankreno** [comment]
@mfornasa : I have not had any cycles to work on this and may not for a couple of weeks.  However, I am open to a PR.  We should be be able to use a similar flow to that was done for the source.containers.conf in most cases.  Some may require some more work.

**Comment by frankreno** [comment]
@mfornasa: The image with the fix for this is now in docker hub.  Thanks for your help @flah00!

**Comment by mfornasa** [comment]
Tried:
```
   - name: EXCLUDE_PATH
          value: "/mnt/log/kube-apiserver.log"
```

Seems good. Thanks.
