### ISSUE TITLE
__sourceCategory and _sourceName are not populated

### ISSUE THREAD

**Issue by mfornasa** [SumoLogic/fluentd-kubernetes-sumologic#2]
I installed the plugin according to the README.
`__sourceCategory` and `_sourceName` are not populated in Sumologic (they are defaults). According to the README they should be populated (e.g., `"%{namespace}.%{pod}.%{container}"`).

Any suggestion on how to debug this?

**Comment by stevezau** [comment]
Ah, yes that was a bug. Please try the latest version. I just pushed to dockerhub.

**Comment by mfornasa** [comment]
Works now. Thanks.
