### ISSUE TITLE
Push versioned images to docker hub.

### ISSUE THREAD

**Issue by carsonoid** [SumoLogic/fluentd-kubernetes-sumologic#24]
Right now it appears that there is only a "latest" tag: https://hub.docker.com/r/sumologic/fluentd-kubernetes-sumologic/tags/

It would be helpful to have a versioned tag pushed as well.

**Comment by ferminromero** [comment]
I agree -- Always pulling the latest image is not ideal for us.

**Comment by adrianchifor** [comment]
Yes please.

**Comment by frankreno** [comment]
We have started tagging, current working version was tagged as v1.0 and others will be tagged as needed.  This is now available in DockerHub
