### ISSUE TITLE
Support for the helm chart? 

### ISSUE THREAD

**Issue by flah00** [SumoLogic/fluentd-kubernetes-sumologic#26]
Does anyone at sumologic have any interest in participating as a reviewer, for the new [sumologic-fluentd](https://github.com/kubernetes/charts/pull/913) chart? Having someone from sumo able to review changes would help keep the chart relevant.

**Comment by frankreno** [comment]
@flah00 : we would be happy to do this.  it has been on our radar to get a helm chart created so thankl you for doing that! Feel free to add me as a reviewed to the PR.
