### ISSUE TITLE
kubernetes 1.6 log location

### ISSUE THREAD

**Issue by agonzalez-tk** [SumoLogic/fluentd-kubernetes-sumologic#34]
seems like on newer version of kubernetes logs are located on /var/log/containers but they are only symbolic links to /var/log/pods, so this is causing error reading, maybe we should change the default mounting point to /var/log instead of /mnt/log

**Comment by frankreno** [comment]
Hi @agonzalez-tk : we are using k8s 1.6 and this has been tested against 1.6.  Can you provide your Daemonset config so I can inspect?

**Comment by frankreno** [comment]
closing - no response. Please re-open if still an issue.
