### ISSUE TITLE
Feature request: Allow the container to use the credentials to talk to the Kubernetes API

### ISSUE THREAD

**Issue by anhnk** [SumoLogic/fluentd-kubernetes-sumologic#35]
Howdy from down-under,

@lucaswilric and I are working on using this fluentd-kubernetes-sumologic container to forward our application logs to Sumologic. The problem we are having at the moment is the container is not authorised to talk to the Kubernetes API. Here is the log from one of the fluentd pods:
```
2017-08-03 01:49:19 +0000 [info]: reading config file path="/fluentd/etc/fluent.file.conf"
2017-08-03 01:49:19 +0000 [error]: config error file="/fluentd/etc/fluent.file.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint [OUR_INTERNAL_DNS_CONTROLLER_NAME]:443/api: 401 Unauthorized"
```

We would like to request a feature to allow the container to use an SSL client certificate to talk to the Kubernetes API. Let me know if you need any other information.

Cheers,

**Comment by frankreno** [comment]
@anhnk : thanks for the request. I am not sure when I will have time to work on this, but would gladly welcome a PR if you feel like taking this on.

**Comment by frankreno** [comment]
fixed by https://github.com/SumoLogic/fluentd-kubernetes-sumologic/commit/b7fc18ba8f254d6404ce59280789e8ab92eca72a
