### ISSUE TITLE
Multiline regex doesn't seem to work

### ISSUE THREAD

**Issue by weaseal** [SumoLogic/fluentd-kubernetes-sumologic#36]
Hello,
I am attempting to use the new multi-line feature without much success. 

I set this environment var:
        - name: MULTILINE_START_REGEXP
          value: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d+

So I would expect any lines following such a line, that do not start with a formatted date, to be included in the previous message.  But still, each "newline" seems to create a separate log entry in sumo, even if it did not start with a date string.

Here is a sample message that should match:

`2017-08-09 17:11:58.522 [INFO] [De-Obfuscator] \stacktrace\:\Mon May 16 10:28:02 GMT-700 2016 MobClient`

So I expect until we see another date like that, all following messages should be part of this message.  But they are not, they are each sent as unique log entries, for example, here is the next message, which did not get grouped with the above:

`SEVERE: Possible problem with your *.gwt.xml module file.`

Am I doing something wrong?  Is it a bug in the handling of multiline messages?

**Comment by frankreno** [comment]
@weaseal : the multi line feature has not been merged yet so won't work with any of the images in DockerHub.  I assume you built a new image and are testing with that?

**Comment by weaseal** [comment]
actually, it does seem to work, I just restarted the pods and it started working
