### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by adrianchifor** [SumoLogic/fluentd-kubernetes-sumologic#37]
Can you guys confirm why the docker image size is almost 10x the size of v1.0? Seems to be mostly because the base fluentd image is now using debian?

We are looking at updating our collector from v1.0 to v1.4 but don't see any major fixes or benefits (a changelog would be nice)

**Comment by frankreno** [comment]
@adrianchifor : yes the reason for the increased size is the change to the new base image.  This change was done to add support for systemd.  v1.0 did not allow for collecting from systemd, only in_tail.

**Comment by frankreno** [comment]
I will add a changelog to the readme.

**Comment by frankreno** [comment]
changelog has been added
