### ISSUE TITLE
Filter kubernetes_sumologic not found

### ISSUE THREAD

**Issue by jaygorrell** [SumoLogic/fluentd-kubernetes-sumologic#4]
I believe either the plugin registration name needs changed to `kubernetes_sumologic_containers` or the file needs changed to `filter_kubernetes_sumologic.rb`. I'm curious why others didn't experience this though so perhaps it's something environmental.

**Comment by stevezau** [comment]
Hey @jaygorrell

That's weird, where are seeing this?

**Comment by jaygorrell** [comment]
I'm just updating things from the old repo and kept getting a startup error/crash from Fluentd stating that the `kubernetes_sumologic` filter doesn't exist.

Plugin registration in filter_kubernetes_sumologic_containers.rb:
`Fluent::Plugin.register_filter('kubernetes_sumologic', self)`

I was able to fix this by renaming the file to `filter_kubernetes_sumologic`... is this not a standard Fluent requirement?

**Comment by stevezau** [comment]
I've renamed it to filter_kubernetes_sumologic but the plugin name is kubernetes_sumologic which is standard reading http://docs.fluentd.org/v0.12/articles/plugin-development
