### ISSUE TITLE
Fluentd only runs on worker nodes

### ISSUE THREAD

**Issue by AlexB138** [SumoLogic/fluentd-kubernetes-sumologic#42]
Per the README, the intention of the pod is to "run an instance of this container on each physical underlying host in the cluster". As of Kubernetes 1.6, the pods will only run on the worker nodes, due to the built in taint on masters.

I see two ways to solve this. Which is best depends on the maintainers intentions:

1. Add a toleration for the built in master taint, _node-role.kubernetes.io/master:NoSchedule_. This will cause fluentd to also schedule on the master and ship its logs.
2. Add the global toleration _operator: "Exists"_. This would cause the fluentd pod to schedule on any node in a cluster, regardless of taints. This is a good bit more aggressive, but would match to stated intention.

Happy to do a PR to fix this if desired.

**Comment by AlexB138** [comment]
Reference the following post and doc for information about taints:

https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
http://blog.kubernetes.io/2017/03/advanced-scheduling-in-kubernetes.html

**Comment by AlexB138** [comment]
Alternatively, a section could just be added to the README explaining how to add the toleration to schedule onto masters/other tainted nodes.

**Comment by frankreno** [comment]
@AlexB138 : considering that the plugin (prior to 1.6) ran on the Nodes and Master without extra config, I am inclined to modify the settings to preserve that behavior.  I prefer option 1 as it is less aggressive.  I still think we need to update the docs for handling scenario 2 on other tainted nodes but by default we should collect from the master as that is where some of the k8s system pods run.  Do you agree?

**Comment by AlexB138** [comment]
@frankreno Yep, I agree on both counts.

I'll put together a PR asap.

**Comment by AlexB138** [comment]
PR is up. Sorry for the delay!

**Comment by frankreno** [comment]
fixed by #43 thanks again!
