### ISSUE TITLE
Multiple Files Tailed and Processed in Parallel?

### ISSUE THREAD

**Issue by andrews32** [SumoLogic/fluentd-kubernetes-sumologic#44]
Can fluentd tail multiple large (and small) files in parallel? Reading this link seems like its only designed for 1 file at a time: https://github.com/fluent/fluentd/issues/573. This seems to support the behavior of the fluentd logs.

We're trying to use with with Red Hat's OpenShift and the number of logs, along with the size, changes at any given time.

**Comment by frankreno** [comment]
relates to #45.

**Comment by andrews32** [comment]
I just experienced this in recent weeks. I don't think #44 relates to #45. #45 seems to be about SumoLogic throttling the customers account and only allowing a percentage of the traffic to enter as long as it keeps the account quota under the cap. This is is more an Accounting/Finance issue than a application issue.

#44 one is about fluentd using the in_tail plugin to tail multiple logs in parallel. In further reading, it seem that is just how in_tail works.

The problem was in /var/log/containers/*.log we had say 10 different logs but only 1 fluentd running. The fluentd would get stuck on the first high volume log and unable to get to the other 9 logs. Once traffic slowed and fluentd got to the end of log the first log, it would go to the next log. The problem was by the time fluentd go to logs 2-10 they already rotated and that data was lost.

I ended up running 10 fluentd daemonsets, each dedicated to 10 different type of application logs. Feel free to close out #44 now.
