### ISSUE TITLE
Restarting collection pods causes massive log delivery and duplicates

### ISSUE THREAD

**Issue by mfornasa** [SumoLogic/fluentd-kubernetes-sumologic#47]
We run this collector on a cluster generating ~5 millions log messages per day.
We recently encountered stability issues, so we are experimenting with the parameters (in particular the number of threads). However, each time we restart the pods to try a new param set:

* A lot of (duplicate) messages are sent. In our case, the collector tries to send ~1 million messages at once, causing high CPU usage, and hitting Sumologic rate limiting.
* After the spike, Sumologic limits us, so delivery is blocked for some time.

The resulting collection usage is the following:

![image](https://user-images.githubusercontent.com/280285/34630773-cb6b85d6-f26d-11e7-9dc6-f7428887f8a8.png)

1. A burst of 1 million messages is sent
1. Sumologic limits us to zero for some time
1. We resume normal collection (small bars)

Small bars are our *real* log production rate (around 1k messages per minute).
  
This behaviour is highly unstable.

**Comment by mfornasa** [comment]
The cause is here: https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/daemonset/rbac/fluentd.yaml#L54. You're using an `emptyDir` volume, which is scrapped when a pod is deleted.

**Comment by frankreno** [comment]
@mfornasa correct right now we do not use a persistent volume.  That is something we can look into adding as configurable.  We would certainly welcome a PR for this kind of change. However, you could also look at leveraging the READ_FROM_HEAD environment variable to control to prevent reading from the head of the file during restarts.

**Comment by frankreno** [comment]
@mfornasa: now that Kubernetes 1.8 has been around for a bit, I have switched to using hostPath persistence for the pos files, which will ensure on restart, fluentD picks up from where it left off.  See #70.
