### ISSUE TITLE
kubelet logs not being captured

### ISSUE THREAD

**Issue by darend** [SumoLogic/fluentd-kubernetes-sumologic#48]
## Issue

We are deploying fluentd-kubernetes-sumologic using the helm chart to a standard kops cluster. The documentation indicates that kubelet logs should be captured by default and can be filtered on using `_sourceName='Http Input'`

When filtering on `_sourceName='Http Input'` the only logs we see are of those of the `fluentd-kubernetes-sumologic` containers.

## Environment

- [sumologic-fluentd chart](https://github.com/kubernetes/charts/tree/master/stable/sumologic-fluentd) 0.2.1
- HTTP Collector with default settings
- kops 1.8.0

**Comment by frankreno** [comment]
@darend to better assist you, please let me know the following:

1) What version of k8s?

**Comment by frankreno** [comment]
@darend just saw you had the k8s version, apologies.  Just the image tag and any changes to default would be helpful.

**Comment by frankreno** [comment]
@darend I just did some research on this and it seems that the kubelet log is no longer available.

https://github.com/kubernetes/kubernetes/issues/26726

At one point it was, but I confirmed in my workers/masters that /var/log/kubelet.log no longer exists. I assume it will be the same for you if you SSH to one of your nodes. Can you confirm?

**Comment by darend** [comment]
> At one point it was, but I confirmed in my workers/masters that /var/log/kubelet.log no longer exists. I assume it will be the same for you if you SSH to one of your nodes. Can you confirm?

Confirmed. That is unfortunate, and with no updates in almost 2 years its unlikely to be restored.

Should we switch `FLUENTD_SOURCE` from `file` to `systemd` to enable capturing logs via journal?  Its not clear from the documentation what the trade off between them is

**Comment by frankreno** [comment]
@darend You can switch the plugin supports both so it should still capture all the same relevant information.  I am going to resolve this issue and a note to the README regarding the fact that kubelet logs are only available via systemD.

**Comment by frankreno** [comment]
Updated readme to indicate findings.

**Comment by darend** [comment]
@frankreno switching the source to `systemd` works. However the documentation needs further update. The kubelet logs will be available as `_sourceName=k8s_kubelet` and docker as `_sourceName=docker`. The images in the [readme](https://github.com/SumoLogic/fluentd-kubernetes-sumologic#kubelet) show it under `_sourceName="HTTP Input"`

**Comment by diversario** [comment]
We're on k8s 1.8.4 and sumo plugin 1.17 but kubelet logs appear as `Http Input`.
