### ISSUE TITLE
Issue with Helm Chart

### ISSUE THREAD

**Issue by Chili-Man** [SumoLogic/fluentd-kubernetes-sumologic#49]
I have a pull request open for the helm chart: 
https://github.com/kubernetes/charts/pull/3453

It is adding support for automatically creating the persistence directory. However, I can't get the tests there to pass because it seems to absolutely require a valid Sumologic endpoint URL. How can I get the tests to without requiring a valid Sumologic endpoint URL for the helm chart?

**Comment by frankreno** [comment]
@Chili-Man thank you for the PR first and foremost.  I am not seeing a clear reason why the tests are now failing but earlier runs have passed.  Let me dive in a bit deeper on the PR request.

**Comment by Chili-Man** [comment]
thanks @frankreno , I'd appreciate the help. I'm grasping at straws here trying to figure it out.

**Comment by frankreno** [comment]
@Chili-Man - I see your multiple re-tests finally passed! Going to close out this issue, thanks for the contribution!
