### ISSUE TITLE
The `merge_json_log` is not compatible with sumo output

### ISSUE THREAD

**Issue by jaygorrell** [SumoLogic/fluentd-kubernetes-sumologic#5]
The sumo output expects `json_merge` but these parameters are sharing an environment variable.

**Comment by stevezau** [comment]
Gm I'll take a look and get back to you

**Comment by stevezau** [comment]
It should still work if you set the env var to `json_merge`. The kubernetes sumo plugin just passes the value to the output plugin, it does nothing with it.

I've updated the README
