### ISSUE TITLE
Inconsistent descriptions for FlushInterval default

### ISSUE THREAD

**Issue by darend** [SumoLogic/fluentd-kubernetes-sumologic#52]
## Isssue

The README says the default **FlushInterval** is 30s, however [values.yaml](https://github.com/kubernetes/charts/blob/d968810a3a30bfd22930ff229272c9a9146e4fe1/stable/sumologic-fluentd/values.yaml#L35) lists the default as 5s

## Expected

Identify correct default and make the documentation consistent

**Comment by frankreno** [comment]
@darend, yes the Helm chart has a different default value that this repo.  The docker image is set to 30s.  The YAML files in this repo do not set the defaults.  Honestly this was an oversight, a bug was discovered where the docs said 5s in this repo, but the Dockerfile was set to 30 seconds.  However, for backwards compatability, we have not pushed a new release that changes that.  More waiting until we have more features to collect so yes the Helm chart and YAML in this repo are not in sync at the moment.

**Comment by frankreno** [comment]
fixed with v1.8
