### ISSUE TITLE
Log locations don't match in Kubernetes setup with Rancher

### ISSUE THREAD

**Issue by ryanwalls** [SumoLogic/fluentd-kubernetes-sumologic#6]
I used Rancher to setup my Kubernetes cluster.  Not sure how the rancher config changed the default k8s configuration, but the logs are not where this plugin expects them to be.  

e.g.  
The fluentd source is configured to tail containers like this:
```
<source>
  type tail
  format json
  time_key time
  path /mnt/log/containers/*.log
  pos_file /mnt/pos/ggcp-containers.log.pos
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag containers.*
  read_from_head false
</source>
```

But there is no `containers` folder in `/mnt/log`.  

Here is a list of all the `containers` folders on my host:
```
ubuntu@ip-172-31-25-18:~$ sudo find / -name "containers"
/var/lib/docker/containers
/var/lib/docker/aufs/diff/2fa0c69c939c136de5ca69d79d6e852d5f7b04ff4f52ef1c354b6952662f0d1b/var/log/containers
/var/lib/docker/aufs/mnt/2fa0c69c939c136de5ca69d79d6e852d5f7b04ff4f52ef1c354b6952662f0d1b/var/log/containers
/var/lib/kubelet/pods/fc1f8008-eaf1-11e6-baef-5ed5f3051185/containers
/var/lib/kubelet/pods/3b7825b5-eaf2-11e6-baef-5ed5f3051185/containers
```

And the only one of those that seems to match the regex for the containers filter is:
```
/var/lib/docker/aufs/mnt/2fa0c69c939c136de5ca69d79d6e852d5f7b04ff4f52ef1c354b6952662f0d1b/var/log/containers
```

Not sure how to proceed from here...  I'm new to fluentd, so doing more research.

The docker config and kubernetes configs don't work either.  On my setup none of these exist:
`/mnt/log/salt/minion`
`/mnt/log/docker.log`

**Comment by ryanwalls** [comment]
Figured out the problem.  See here: https://github.com/rancher/rancher/issues/7688

Basically, since rancher runs the kubelet in a container, the `/var/log/containers` directory is created inside the container.  Therefore without mounting a volume, it is not available to the `fluentd-kubernetes-sumologic` container.

**Comment by stevezau** [comment]
There is not much we can do if the logs are not available. Closing this for now.
