### ISSUE TITLE
Feature request: Allow the ability to data forward to S3 at the fluentD plugin level 

### ISSUE THREAD

**Issue by alexbklein91** [SumoLogic/fluentd-kubernetes-sumologic#63]
I want the ability to "T" (data forward) my data to sumo logic and another source like s3 at the fluentD plugin level. The use case here is if I want to filter certain data that I send to Sumo Logic, but I want a back up of all my data I need this ability.

**Comment by voxxit** [comment]
@alexbklein91 Can you try out my fork in #71, and ensure it works for your use case?
