### ISSUE TITLE
FEATURE REQUEST: Add variable for INCLUDE_PATH

### ISSUE THREAD

**Issue by andrews32** [SumoLogic/fluentd-kubernetes-sumologic#64]
Similar to EXCLUDE_PATH, would like the reverse ability to set the INCLUDE_PATH.

Problem is the in_tail plugin can only read one log at a time. When there are multiple logs on the same host, we need to run multiple copies of the fluentd-kubernetes-sumologic container. Each one is dedicated to a certain log. Be nice to just pass a parameter to specify each log.

I believe it currently is set as "path /mnt/log/containers/*.log" in https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/conf.d/file/source.containers.conf.

**Comment by frankreno** [comment]
added in v1.5/latest.  See environment variables in readme for configuration.

**Comment by andrews32** [comment]
Thanks, CONTAINER_LOGS_PATH is working great!
