### ISSUE TITLE
fluentd proxy support

### ISSUE THREAD

**Issue by rajmechi** [SumoLogic/fluentd-kubernetes-sumologic#65]
fluentd sumologic plugin support proxy but fluentd-kubernetes-sumologic daemonset does not support the proxy. please add support for proxy variable.

"The install guide ( https://github.com/SumoLogic/fluentd-kubernetes-sumologic ) does not mention supporting proxy settings but the Sumologic plugin (  https://github.com/SumoLogic/fluentd-output-sumologic ) for kubernetes does"

**Comment by huddlesj** [comment]
Following

**Comment by frankreno** [comment]
fixed in v1.5/latest.  See environment variables in readme for configuration.
