### ISSUE TITLE
`pos-files` appears to map to empty directory

### ISSUE THREAD

**Issue by greenkiwi** [SumoLogic/fluentd-kubernetes-sumologic#70]
It appears that the the positional files are mapped to an empty directory even though there is a volume mounted for them.  This would suggest that every time the fluend pod gets recreated it would start from the beginning of available logs.  We had this happen and it uploaded 300gb of duplicated logs as fast as fluent could send them.

Mapping
```
      volumes:
      - name: pos-files
        emptyDir: {}
```
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/master/daemonset/rbac/fluentd.yaml#L55

Is there any reason not to map this into the node's filesystem?

**Comment by frankreno** [comment]
@greenkiwi thanks for the issue.  The only reason we did not add this in the past was it `hostPath` was only available in 1.8 so wanted to keep things backward compatible.  However, now that k8s on 1.11 and `hostPath` has been around for some time, I think its time to address this once and for all to remove that pain point you had.  I will get this added to the yaml and update the readme accordingly.

**Comment by frankreno** [comment]
Also side note, if you use the Helm chart to deploy, there is an option for persistence https://github.com/kubernetes/charts/tree/master/stable/sumologic-fluentd.

**Comment by frankreno** [comment]
This is now fixed in the YAML, readme updated with instructions for running plugin on Kubernetes <1.8. https://github.com/SumoLogic/fluentd-kubernetes-sumologic/commit/65efc181c17685e327be409ec7701d08587073d4

**Comment by greenkiwi** [comment]
@frankreno Thanks.  We'll be updating.  Much appreciated.
