### ISSUE TITLE
READ_FROM_HEAD=false Doesn't Read Header of New Logs

### ISSUE THREAD

**Issue by andrews32** [SumoLogic/fluentd-kubernetes-sumologic#72]
Even with **READ_FROM_HEAD=false**, shouldn't fluentd still read all lines (even the header) of logs created after the start of fluentd? For example, fluentd is fully up and running. Well afterwards, a new application container is started, which creates a new log:

1. Starting container...
2. Initializing X...
3. Initializing Y...
4. Initializing Z...
...
33.  Container started in 30 seconds...
34. Data 
35. Data
...
96. Data
97. Data
98. Application log entries
99. Shutting down container...
100. Container stopped.

The problem I'm seeing is fluentd is not forwarding the first few lines of the log (lines 1-33 in the above example). The rest of the log (lines 34 -100) are forwarded normally.

**Comment by frankreno** [comment]
@andrews32 no not necessarily.  READ_FROM_HEAD has to be set to true to ensure we always read from the top of the log file.  If it is false, per the FluentD docs it will read from the bottom of the file.
https://docs.fluentd.org/v0.12/articles/in_tail#read_from_head
