### ISSUE TITLE
Add support for GKE node pools with GPUs attached

### ISSUE THREAD

**Issue by zanthorn** [SumoLogic/fluentd-kubernetes-sumologic#73]
I have an app/container that uses a GPU for machine learning processes running on kubernetes in GCP. One cool feature about GPU node pools in GKE is that pods will only be placed on the node pool if the pod is requesting GPU resources. This is good in most scenarios, but in the case of this Sumo plugin, it means logs from pods on the GPU node pool never gets collected since the Sumo pod won't ever be scheduled on those nodes.

https://cloud.google.com/kubernetes-engine/docs/how-to/gpus
>This causes only Pods requesting GPUs to be scheduled on GPU nodes, which enables more efficient autoscaling: your GPU nodes can quickly scale down if there are not enough Pods requesting GPUs.

I would love to see support added for scheduling the Sumo Flutentd pods on GPU node pools running in GCP.

**Comment by frankreno** [comment]
@zanthorn you should be able to do this by simply adding a toleration to support the Taint GKE uses on the GPU nodes.  Can you try adding this to the tolerations in the YAML and see if they get scheduled?

          - operator: "Exists"
          - effect: "NoSchedule"
            key: "nvidia.com/gpu"

**Comment by zanthorn** [comment]
That did it, thanks for the fast response!
