### ISSUE TITLE
instructions for running on openshift are confusing 

### ISSUE THREAD

**Issue by rajmechi** [SumoLogic/fluentd-kubernetes-sumologic#77]
hey @frankreno 
in docker hub (https://hub.docker.com/r/sumologic/fluentd-kubernetes-sumologic/ ) mentioned below for openshift
oc adm policy add-scc-to-user privileged system:serviceaccount:logging:sumologic-fluentd
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:sumologic-fluentd
**service account is sumologic-fluentd and project is logging

but in actual fluentd.yml, service account pointing to fluentd
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L52
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L5
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L11

**Comment by rajmechi** [comment]
in docker hub (https://hub.docker.com/r/sumologic/fluentd-kubernetes-sumologic/ ) mentioned below  for openshift
oc adm policy add-scc-to-user privileged system:serviceaccount:logging:sumologic-fluentd
oc adm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:sumologic-fluentd
**service account is sumologic-fluentd and project is logging

but in actual fluentd.yml, service account pointing to fluentd
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L52
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L5
https://github.com/SumoLogic/fluentd-kubernetes-sumologic/blob/v1.18/daemonset/rbac/fluentd.yaml#L11

**Comment by frankreno** [comment]
@rajmechi thanks, I updated the readme to ensure the service account name matches.
