### ISSUE TITLE
Getting failed connections to sumologic endpoint

### ISSUE THREAD

**Issue by ryanwalls** [SumoLogic/fluentd-kubernetes-sumologic#8]
Here's my sumologic output config:

```
<match **>
 type sumologic
 log_key log
 endpoint https://endpoint1.collection.us2.sumologic.com/receiver/v1/http/<not showing this>
 verify_ssl 
 log_format json
 flush_interval 30s
 num_threads 1
</match>
```

And here's the error I'm getting:
```
temporarily failed to flush the buffer. next_retry=2017-02-07 14:11:19 +0000 error_class="SocketError" error="Failed to open TCP connection to endpoint1.collection.us2.sumologic.com:443 (getaddrinfo: Name does not resolve)" plugin_id="object:3fa92374c7f8"
2/7/2017 7:07:08 AM  2017-02-07 14:07:08 +0000 [warn]: suppressed same stacktrace
```

**Comment by ryanwalls** [comment]
This is due to problems that Alpine has with specific DNS settings.  See https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md#dns.  And try googling alpine DNS issues... not sure what the solution is.  But not your problem.  Closing.

**Comment by ryanwalls** [comment]
A potential workaround: https://github.com/janeczku/docker-alpine-kubernetes

**Comment by ryanwalls** [comment]
Reopening... as I haven't figured out a way around this.  Tried the base image I linked to with no success.  I would think this would happen with most k8s setups?

**Comment by stevezau** [comment]
This is a dns issue, it cannot resolve endpoint1.collection.us2.sumologic.com which is a FQDN.. I don't think it has anything to do with this repo.

**Comment by ryanwalls** [comment]
@stevezau True, except that we need to provide the sumologic URL for this repo to work properly.  Should I just provide an IP? 

The problem is because this image is based on the fluentd container, which is based on Alpine, which doesn't work with k8s networking... 

How did you work around it in your k8s setup?

**Comment by stevezau** [comment]
@ryanwalls We have it running on a cluster with 5 nodes running 400 containers.. other customers are using it as well.

You cant use a IP as it's an AWS ELB so the IP will change. 

It's just standard dns so i can't see why it wouldn't work?

**Comment by ryanwalls** [comment]
OK. Will close for now. Genuinely, thanks for your help.  Here is a good link to other people with the same issue. Not sure what we have in common yet. https://github.com/gliderlabs/docker-alpine/issues/8

**Comment by ryanwalls** [comment]
@stevezau FYI, used the debian image for fluentd that is in progress here https://github.com/fluent/fluentd-docker-image/pull/71 and was able to get this working without a hitch.  Thanks for a great tool!  

Food for thought... may want to use the debian based fluentd image when it gets merged.

**Comment by ryanwalls** [comment]
@stevezau Debian images for fluentd have been merged.
