### ISSUE TITLE
Disable Watch on Kubernetes Metadata Filter Plugin

### ISSUE THREAD

**Issue by salilgupta1** [SumoLogic/fluentd-kubernetes-sumologic#80]
The https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter has a watch functionality that watches for all pods in the system and caches the metadata of all pods. However, we've seen in our testing with our other fluentd collector that this OOM kills the fluentd container since the cache quickly fills up. This is pretty easy to run into especially with large clusters like ours (700+ nodes, 10k+ pods). We fixed this issue by disabling the watch functionality. Below is a code snippet of how to do that: 

```
    <filter user.**>
      @type kubernetes_metadata
      tag_to_kubernetes_name_regexp '.+?\.containers\.(?<pod_name>[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$'
      watch false
      de_dot false
      annotation_match ["^civis\.io\/.*"]
    </filter>
```

Can we expose this setting as an environment variable for this image?

**Comment by frankreno** [comment]
@salilgupta1 yes we can add this, as part of addressing #79, I will expose this setting and other settings that are not currently exposed to provide more control of the metadata filter plugin.

**Comment by frankreno** [comment]
@salilgupta1 `v1.2.0` and `latest` will contain these changes.
