### ISSUE TITLE
exclude/include issue

### ISSUE THREAD

**Issue by amiraBN** [SumoLogic/fluentd-kubernetes-sumologic#82]
Hi,

Using the kubectl install for fluentD plugin I was trying to exclude all namesapces excepting one pod .

I had to add the following line into the fluentd.yaml file under the env section in order to exclude every namespaces 
"name": "EXCLUDE_NAMESPACE_REGEX",
						"value": ".*"

and after that I added the annotation "sumologic.com/include": "true"  in the pod.yaml file in order to only get the logs of this pod but still not having any logs into Sumologic. is there any missing part in this configuration to fix in order to get logs?

**Comment by amiraBN** [comment]
to be more specific I was using a json format for fluentd file instead of yaml

**Comment by amiraBN** [comment]
I tried also to be more specific in the regex expression with naming the namepsaces to exclude using that:
{
"name": "EXCLUDE_NAMESPACE_REGEX",
"value": "name_space1|name_space2|name_space3|"
}
I mentioned this exclusion in the fluentd.json and  sumologic-k8s-api-cronjob-rbac.yaml files undre env section
but still getting logs from excluded namespaces

**Comment by amiraBN** [comment]
@frankreno , this is the kubernetes version 
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.9", GitCommit:"3fb1aafdafa3d33bc698930095db1e56c0f76452", GitTreeState:"clean", BuildDate:"2018-03-12T16:13:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

this is the fluentD json file 

`
---
{
   "apiVersion": "v1",
   "kind": "ServiceAccount",
   "metadata": {
      "name": "fluentd"
   }
}
---
{
   "apiVersion": "rbac.authorization.k8s.io/v1beta1",
   "kind": "ClusterRole",
   "metadata": {
      "name": "fluentd"
   },
   "rules": [
      {
         "apiGroups": [
            ""
         ],
         "resources": [
            "namespaces",
            "pods"
         ],
         "verbs": [
            "get",
            "list",
            "watch"
         ]
      }
   ]
}
---
{
  "kind": "ClusterRoleBinding",
  "apiVersion": "rbac.authorization.k8s.io/v1beta1",
  "metadata": {
    "name": "fluentd"
  },
  "roleRef": {
    "kind": "ClusterRole",
    "name": "fluentd",
    "apiGroup": "rbac.authorization.k8s.io"
  },
  "subjects": [
    {
      "kind": "ServiceAccount",
      "name": "fluentd",
	  "namespace": "default"

    }
  ]
}
---
{
   "apiVersion": "extensions/v1beta1",
   "kind": "DaemonSet",
   "metadata": {
      "name": "fluentd-sumologic",
      "labels": {
         "app": "fluentd-sumologic",
         "version": "v1"
      }
   },
   "spec": {
      "template": {
         "metadata": {
            "labels": {
               "name": "fluentd-sumologic"
            }
         },
         "spec": {
            "serviceAccountName": "fluentd",
            "volumes": [
               {
                  "name": "pos-files",
                  "hostPath": {
                     "path": "/var/run/fluentd-pos",
                     "type": ""
                  }
               },
               {
                  "name": "host-logs",
                  "hostPath": {
                     "path": "/var/log/"
                  }
               },
               {
                  "name": "docker-logs",
                  "hostPath": {
                     "path": "/var/lib/docker"
                  }
               }
            ],
            "containers": [
               {
                  "image": "sumologic/fluentd-kubernetes-sumologic:latest",
                  "name": "fluentd",
                  "imagePullPolicy": "Always",
                  "volumeMounts": [
                     {
                        "name": "host-logs",
                        "mountPath": "/mnt/log/",
                        "readOnly": true
                     },
                     {
                        "name": "host-logs",
                        "mountPath": "/var/log/",
                        "readOnly": true
                     },
                     {
                        "name": "docker-logs",
                        "mountPath": "/var/lib/docker/",
                        "readOnly": true
                     },
                     {
                        "name": "pos-files",
                        "mountPath": "/mnt/pos/"
                     }
                  ],
                  "env": [
                     {
                        "name": "COLLECTOR_URL",
                        "valueFrom": {
                           "secretKeyRef": {
                              "name": "sumologic1",
                              "key": "collector-url"
                           }
                        }
                     },
					 {
						"name": "EXCLUDE_NAMESPACE_REGEX",
						"value": "api|backup|basex-test|conductor|conductor-bridge|conductor-clement|conductor-loic|conductor-test1|core|db-conductor-dynomite|db-conductor-es|db-conductor-redis|db-main-mongo|db-main-mysql|default|front|grafana|heptio-ark|java-legacy|kube-public|kube-system|logging|maintenance|micro-service|operation|prometheus|test-openvpn|tasks|test1|worker|sandbox"
					 }
                  ]
               }
            ],
            "tolerations": [
               {
                  "effect": "NoSchedule",
                  "key": "node-role.kubernetes.io/master"
               }
            ]
         }
      }
   }
}

`

**Comment by amiraBN** [comment]
@frankreno , this is the kubernetes version 
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.9", GitCommit:"3fb1aafdafa3d33bc698930095db1e56c0f76452", GitTreeState:"clean", BuildDate:"2018-03-12T16:13:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
this is the fluentD json file
---
{
   "apiVersion": "v1",
   "kind": "ServiceAccount",
   "metadata": {
      "name": "fluentd"
   }
}
---
{
   "apiVersion": "rbac.authorization.k8s.io/v1beta1",
   "kind": "ClusterRole",
   "metadata": {
      "name": "fluentd"
   },
   "rules": [
      {
         "apiGroups": [
            ""
         ],
         "resources": [
            "namespaces",
            "pods"
         ],
         "verbs": [
            "get",
            "list",
            "watch"
         ]
      }
   ]
}
---
{
  "kind": "ClusterRoleBinding",
  "apiVersion": "rbac.authorization.k8s.io/v1beta1",
  "metadata": {
    "name": "fluentd"
  },
  "roleRef": {
    "kind": "ClusterRole",
    "name": "fluentd",
    "apiGroup": "rbac.authorization.k8s.io"
  },
  "subjects": [
    {
      "kind": "ServiceAccount",
      "name": "fluentd",
	  "namespace": "default"

    }
  ]
}
---
{
   "apiVersion": "extensions/v1beta1",
   "kind": "DaemonSet",
   "metadata": {
      "name": "fluentd-sumologic",
      "labels": {
         "app": "fluentd-sumologic",
         "version": "v1"
      }
   },
   "spec": {
      "template": {
         "metadata": {
            "labels": {
               "name": "fluentd-sumologic"
            }
         },
         "spec": {
            "serviceAccountName": "fluentd",
            "volumes": [
               {
                  "name": "pos-files",
                  "hostPath": {
                     "path": "/var/run/fluentd-pos",
                     "type": ""
                  }
               },
               {
                  "name": "host-logs",
                  "hostPath": {
                     "path": "/var/log/"
                  }
               },
               {
                  "name": "docker-logs",
                  "hostPath": {
                     "path": "/var/lib/docker"
                  }
               }
            ],
            "containers": [
               {
                  "image": "sumologic/fluentd-kubernetes-sumologic:latest",
                  "name": "fluentd",
                  "imagePullPolicy": "Always",
                  "volumeMounts": [
                     {
                        "name": "host-logs",
                        "mountPath": "/mnt/log/",
                        "readOnly": true
                     },
                     {
                        "name": "host-logs",
                        "mountPath": "/var/log/",
                        "readOnly": true
                     },
                     {
                        "name": "docker-logs",
                        "mountPath": "/var/lib/docker/",
                        "readOnly": true
                     },
                     {
                        "name": "pos-files",
                        "mountPath": "/mnt/pos/"
                     }
                  ],
                  "env": [
                     {
                        "name": "COLLECTOR_URL",
                        "valueFrom": {
                           "secretKeyRef": {
                              "name": "sumologic1",
                              "key": "collector-url"
                           }
                        }
                     },
					 {
						"name": "EXCLUDE_NAMESPACE_REGEX",
						"value": "api|backup|basex-test|conductor|conductor-bridge|conductor-clement|conductor-loic|conductor-test1|core|db-conductor-dynomite|db-conductor-es|db-conductor-redis|db-main-mongo|db-main-mysql|default|front|grafana|heptio-ark|java-legacy|kube-public|kube-system|logging|maintenance|micro-service|operation|prometheus|test-openvpn|tasks|test1|worker|sandbox"
					 }
                  ]
               }
            ],
            "tolerations": [
               {
                  "effect": "NoSchedule",
                  "key": "node-role.kubernetes.io/master"
               }
            ]
         }
      }
   }
}

**Comment by frankreno** [comment]
@amiraBN thanks for the additional information over email, looks like you have everything configured properly, and I am still unable to reproduce this.  I would like you to try a few more things and if these do not work, suggest we have a call:

**Comment by amiraBN** [comment]
@frankreno  I resolved the issue for the fluentd plugin it seems that it was a  missconfiguration in the annotation.

**Comment by frankreno** [comment]
great glad to hear!
