### ISSUE TITLE
Does latest version comes with rewrite_tag_filer plugin

### ISSUE THREAD

**Issue by purva1192** [SumoLogic/fluentd-kubernetes-sumologic#85]
I am new to this plugin and trying to work around a problem. I am using v1.2.0 to route some logs to AWS S3 bucket. I read up on that and thought of using the `rewrite_tag_filter`. However I get the error

```
error_class=Fluent::ConfigError error="Unknown output plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
```

Guess my question is does this plugin come with the `out_rewrite_tag_filter`?

**Comment by frankreno** [comment]
it does not, only fluent-plugin-s3.  The example configuration on our README should not require the rewrite tag in its current state.  Can you share some more about your use case for `rewrite_tag_filter`?

**Comment by purva1192** [comment]
Well my use case is -
I wanted to tag logs matching a particular "message" and then use that tag to copy the logs to s3 bucket. Is there a better way to do this without using the `rewrite_tag_filter`. 
As mentioned I am new to the plugin, so any insights are appreciated.

**Comment by frankreno** [comment]
Ok, I see, so yeah to do store just a subset, you would need the rewrite tag filter.  I am planning a release for later this week to address #79 and I can add that plugin to the docker file then.  That use case is common enough I think it is good to add to make available to the Docker file.

**Comment by purva1192** [comment]
Awsome!! That sounds great!! That works for me..

**Comment by frankreno** [comment]
This plugin is now part of the image in v2.0.0
