### ISSUE TITLE
fluentd not posting log to collector

### ISSUE THREAD

**Issue by viveksoundrapandi** [SumoLogic/fluentd-kubernetes-sumologic#86]
I have a k8s cluster running with multiple services. I am trying to setup sumo logic to my cluster. I installed this helm chart and logs are streamed to the collector from all services except for one service.

I am able to tail the logs of the pod from shell. But the logs are not getting collected in the collector.
Digging into the logs of sumologic pod all I could see is the below log statment:

```
2018-10-12 05:47:08 +0000 [info]: #0 following tail of /mnt/log/containers/website-6bb5f6d569-v6gxn_default_website-7661e3b9857caa317bc9a5d82d82183f7202cafae177665b15d3bc024bfed730.log

2018-10-12 06:00:47 +0000 [warn]: #0 failed to flush the buffer. retry_time=0 
next_retry_seconds=2018-10-12 06:00:48 +0000 chunk="57801ce056a36ca1d956ea401c87cbfe" error_class=RuntimeError error="Failed to send data to HTTP Source. 503 - "```


I could not find any documentation regarding this issue. Any help would be appreciated

**Comment by viveksoundrapandi** [comment]
K8s version: 1.10.6-gke.2
fluentd version: fluentd-gcp-v3.1.0
Changes to environment variables: NONE

**Comment by frankreno** [comment]
@viveksoundrapandi: is this consistent or intermittent? How are you searching? The metadata for Kubernetes logs is built dynamically.  If you do a search for `_collector=<INSERT_COLLECTOR_NAME> | count by _sourceCategory` and put the name of the hosted collector you set up, do you see data coming in?

**Comment by frankreno** [comment]
@viveksoundrapandi any updates?

**Comment by viveksoundrapandi** [comment]
@frankreno yes there was an issue in the collector. Thanks for the support. Closing the issue

**Comment by MasterSquishy** [comment]
> @frankreno yes there was an issue in the collector. Thanks for the support. Closing the issue

@viveksoundrapandi We are experiencing this issue as well. Can you please describe the collector issue in greater detail, and the steps that you took to resolve it? Thank you!

**Comment by viveksoundrapandi** [comment]
@MasterSquishy  I had my hosted collected URL wrong. Nothing to do with the helm chart
