### ISSUE TITLE
Use tag as source_name?

### ISSUE THREAD

**Issue by dlaidlaw** [SumoLogic/fluentd-kubernetes-sumologic#88]
Is it possible to use the value of the tag as the source_name in the filter. For example:

```            
             <source>
                @type tail
                format none
                path /mnt/log/my/*.log
                pos_file /mnt/pos/my.pos
                tag my.*
            </source>
            <filter my.**>
                @type kubernetes_sumologic
                source_category "varlog"
                source_name ${tag}
            </filter>
```
How would you write the expression to substitute the value of the tag into the source_name? The tag value in the filter would be something like my.mnt.log.my.install.log.

**Comment by frankreno** [comment]
@dlaidlaw `${tag}` should be the proper syntax.  

Please note that in your current setup you are trying to parse your custom log file thru the `fluentd-kubernetes-plugin`.  This plugin is specifically built just for Kubenetes logs.  If these logs are not originating from Kubernetes, then I would sugged you use our generic fluentD output plugin to deliver the logs straight to sumo. Link below.  The below plugin is packaged with this plugin in the Docker file and it what actually ships the logs to Sumo.

https://github.com/SumoLogic/fluentd-output-sumologic

**Comment by dlaidlaw** [comment]
The ${tag} does not work as shown in my example, nor does it work when wrapped in quotes. But thanks for pointing out that I am using the wrong plugin for this. I works, though.

**Comment by dlaidlaw** [comment]
The ${tag} does not get substituted in this plugin. I have tried this multiple ways, with and without quotes, etc. Can someone verify that it should be supported?

**Comment by frankreno** [comment]
@dlaidlaw : this plugin does not expose the tag that way, but is not intended to be used this way.  This is filter plugin, built to process/enrich Kubernetes logs specifically.  It is preconfigured to send the data to our other FluentD Output plugin which I referenced.  The output plugin does support this.  We have a test that confirm this in the output plugin repo.  Below is the configuration you should be using, don't use this plugin for what you are trying to do.  

```
            <source>
                @type tail
                format none
                path /mnt/log/my/*.log
                pos_file /mnt/pos/my.pos
                tag my.*
            </source>
            <filter my.**>
                @type sumologic
                source_category "varlog"
                source_name ${tag}
            </filter>
```

**Comment by dlaidlaw** [comment]
OK, I am using this in a kubernetes cluster, and was following the examples in the 
        fluentd-kubernetes-sumologic/conf.d/file/source.kubernetes.conf file. That file also tails logs on disk and "filters" them. I just wanted to add another directory of files to the list.

I will try again as you say with the other plugin.

**Comment by dlaidlaw** [comment]
OK, I got it to work. It was a rookie mistake, and I am not a rookie :(  I was writing the helm chart values file using a bash script with a here document and forgot to escape the $.  Very embarrassing.

**Comment by frankreno** [comment]
haha all good, glad you got it working!
