### ISSUE TITLE
Max Log Length

### ISSUE THREAD

**Issue by andrews32** [SumoLogic/fluentd-kubernetes-sumologic#89]
What is the max single log message length?

I have a developer who wrote out a log message that's over 40k characters (~40kb) and 98% of the string got forwarded to Sumo. But its missing the last few hundred characters.

**Comment by frankreno** [comment]
@andrews32 this max log message size on the sumo side is 64kb.  After that sumo will split the message into multiple messages.  If you do a string search on the missing characters, can you find the split message? Is there any errors in the FluentD logs when this happens?

**Comment by andrews32** [comment]
No, I'm not seeing the rest of the message body. Oddly enough, Sumo says it's only 16.8kb, not even close to 64kb.

No errors in fluentd logs either related to the issue.

**Comment by frankreno** [comment]
@andrews32 - Sorry for the delay. If this is still an issue, please open up a Support Case with Sumo Logic Support and reference this issue.  That way I can help debug this further thru those channels.  I will leave this open for now.
