### ISSUE TITLE
Memory Leak in fluentd v1.1.3. (Fixed in v1.1.5)

### ISSUE THREAD

**Issue by NfNitLoop** [SumoLogic/fluentd-kubernetes-sumologic#90]
We noticed that our SumoLogic fluentd pods were getting `SIGKILL`ed.  

Looks like there's a known memory leak in fluentd v1.1.3 (which this Docker image uses):
https://github.com/fluent/fluentd/issues/1941

Should probably upgrade to 1.1.5 (or newer?).

**Comment by frankreno** [comment]
@NfNitLoop thanks for the issue. I will be pushing a new release today or tomorrow hopefully with multiple fixes including upgrading the base FluentD image to 1.2.6.

**Comment by frankreno** [comment]
v2.0.0 has been released with the upgraded image

**Comment by NfNitLoop** [comment]
Are there plans to also update https://github.com/helm/charts/blob/master/stable/sumologic-fluentd/values.yaml to use 2.0.0?

In the meantime, users will have to override the `image.tag` value to v2.0.0 to get the non-memory-leaky image, right?

**Comment by frankreno** [comment]
Yup, Ill be getting a PR together to bring that up to date next week...
