### ISSUE TITLE
Update helm chart

### ISSUE THREAD

**Issue by dorongutman** [SumoLogic/fluentd-kubernetes-sumologic#94]
Version 2.0.0 was released a few days ago, however the helm chart (https://github.com/helm/charts/tree/master/stable/sumologic-fluentd) has version 1.16.

**Comment by frankreno** [comment]
We will be submitting a PR next week to upgrade the chart.  In the meantime, you can pass `--set image.tag=v2.0.0` to install the updated image via help.

**Comment by dorongutman** [comment]
@frankreno thanks, but can I do that as part of an upgrade of an already installed chart ?

**Comment by frankreno** [comment]
you can indeed...i do that all the time w/o reinstalling.  `helm upgrade <chart> --set image.tag=v2.0.0 ...<other flags you want to set> stable/sumologic-fluentd>`.  If you want to force recreate the pods, you can add `--recreate-pods`

**Comment by frankreno** [comment]
most recent image is now the default in the helm chart.
